In [1]:
import os
os.getcwd()

'c:\\Users\\User\\Documents\\ai_and_ml_with_gen_ai_proj\\notebooks'

In [2]:
import sys
sys.path.append(os.path.abspath('..'))

In [3]:
from src.components.data_ingestion import DataIngestion
from src.config.paths import Configuration

config = Configuration().get_config()

In [4]:
from src.components.data_transformation import DataTransformation

In [5]:
print(config)

{'data': {'raw': 'data/raw', 'cleaned': 'data/cleaned', 'processed': 'data/processed'}, 'database': {'schema': 'sql/schema.sql', 'user': 'postgres', 'host': 'localhost', 'port': 5432, 'name': 'olist_brazil_db'}, 'artifacts': {'data': 'artifacts/data', 'metrics': 'artifacts/metrics', 'models': 'artifacts/models', 'preprocessor': 'artifacts/preprocessor'}, 'files': {'customers': 'olist_customers_dataset.csv', 'geolocation': 'olist_geolocation_dataset.csv', 'order_items': 'olist_order_items_dataset.csv', 'order_payments': 'olist_order_payments_dataset.csv', 'order_reviews': 'olist_order_reviews_dataset.csv', 'orders': 'olist_orders_dataset.csv', 'products': 'olist_products_dataset.csv', 'sellers': 'olist_sellers_dataset.csv', 'category_translation': 'product_category_name_translation.csv'}}

In [6]:
ingest = DataIngestion(config= config).initiate_data_ingestion()

In [7]:
df = ingest.Ingested_df

In [10]:
transform = DataTransformation(config, ingest)
transformed_df = transform.feature_eng().transformed_df

PermissionError: [Errno 13] Permission denied: 'C:\\Users\\User\\Documents\\ai_and_ml_with_gen_ai_proj\\data\\processed'

In [ ]:
transformed_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 96470 entries, 0 to 96469
Data columns (total 21 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   customer_state              96470 non-null  str
 1   number_of_items             96470 non-null  int64
 2   number_of_products          96470 non-null  int64
 3   number_of_sellers           96470 non-null  int64
 4   total_price                 96470 non-null  float64
 5   total_freight               96470 non-null  float64
 6   total_product_weight        96454 non-null  float64
 7   total_product_volume        96454 non-null  float64
 8   product_category_name       96470 non-null  str
 9   seller_state                96470 non-null  str
 10  total_payment_value         96469 non-null  float64
 11  max_payment_installments    96469 non-null  float64
 12  number_of_payments          96469 non-null  float64
 13  payment_type                96470 non-null  str
 14  is_late                     96470 non-null  int64
 15  order_purchase_hour         96470 non-null  int32
 16  order_purchase_day_of_week  96470 non-null  int32
 17  order_purchase_month        96470 non-null  int32
 18  order_purchase_year         96470 non-null  int32
 19  order_approval_delay_hours  96456 non-null  float64
 20  estimated_delivery_days     96470 non-null  float64
dtypes: float64(9), int32(4), int64(4), str(4)
memory usage: 14.0 MB

In [ ]:
transformed_df.isnull().sum()

customer_state                 0
number_of_items                0
number_of_products             0
number_of_sellers              0
total_price                    0
total_freight                  0
total_product_weight          16
total_product_volume          16
product_category_name          0
seller_state                   0
total_payment_value            1
max_payment_installments       1
number_of_payments             1
payment_type                   0
is_late                        0
order_purchase_hour            0
order_purchase_day_of_week     0
order_purchase_month           0
order_purchase_year            0
order_approval_delay_hours    14
estimated_delivery_days        0
dtype: int64

:

,order_id,customer_id,customer_unique_id,customer_city,customer_state,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,...,total_product_volume,product_category_name,seller_city,seller_state,total_payment_value,max_payment_installments,number_of_payments,payment_type,average_review_score,is_late
0,00010242fe8c5a6d1ba2dd792cb16214,3ce436f183e68e07877b285a838db11a,871766c5855e863f6eccc05f988b23cb,campos dos goytacazes,RJ,2017-09-13 08:59:02,2017-09-13 09:45:35,2017-09-19 18:34:16,2017-09-20 23:43:48,2017-09-29,...,3528.0,cool_stuff,volta redonda,SP,72.19,2.0,1.0,credit_card,5.0,0
1,000229ec398224ef6ca0657da4fc703e,6489ae5e4333f3693df5ad4372dab6d3,3818d81c6709e39d06b2738a8d3a2474,para de minas,MG,2018-01-14 14:33:31,2018-01-14 14:48:30,2018-01-16 12:36:48,2018-01-22 13:19:16,2018-02-05,...,14157.0,moveis_decoracao,borda da mata,MG,216.87,5.0,1.0,credit_card,5.0,0
2,00024acbcdf0a6daa1e931b038114c75,d4eb9395c8c0431ee92fce09860c5a06,af861d436cfc08b2c2ddefd0ba074622,atibaia,SP,2018-08-08 10:00:35,2018-08-08 10:10:18,2018-08-10 13:28:00,2018-08-14 13:32:39,2018-08-20,...,2400.0,perfumaria,franca,SP,25.78,2.0,1.0,credit_card,4.0,0
3,00042b26cf59d7ce69dfabb4e55b4fd9,58dbd0b2d70206bf40e62cd34e84d795,64b576fb70d441e8f1b2d7d446e483c5,varzea paulista,SP,2017-02-04 13:57:51,2017-02-04 14:10:13,2017-02-16 09:46:09,2017-03-01 16:42:31,2017-03-17,...,42000.0,ferramentas_jardim,loanda,PR,218.04,3.0,1.0,credit_card,5.0,0
4,00054e8431b9d7675808bcb819fb4a32,32e2e6ab09e778d99bf2e0ecd4898718,635d9ac1680f03288e72ada3a1035803,guararapes,SP,2017-12-10 11:53:48,2017-12-10 12:10:31,2017-12-12 01:07:48,2017-12-18 22:03:38,2018-01-04,...,2700.0,telefonia,sao paulo,SP,31.75,1.0,1.0,credit_card,4.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96465,fff8287bbae429a99bb7e8c21d151c41,6c1e92a209dbf868706caa831090941e,028c09f007292c4e3a3b10d296e47987,joao pessoa,PB,2018-03-17 12:11:45,2018-03-17 12:29:22,2018-03-21 19:22:25,2018-04-07 10:07:48,2018-04-19,...,16000.0,informatica_acessorios,jacarei,SP,456.28,4.0,1.0,credit_card,5.0,0
96466,fffa82886406ccf10c7b4e35c4ff2788,a5201e1a6d71a8d21e869151bd5b4085,2a3ab9bf9639491997586882c502540a,tenente ananias,RN,2017-12-18 16:33:07,2017-12-18 17:33:04,2017-12-20 18:55:00,2018-01-08 18:23:10,2018-01-24,...,13500.0,esporte_lazer,pirituba,SP,273.92,7.0,1.0,credit_card,4.0,0
96467,fffb2ef8874127f75b52b643880fd7e0,ca8374c00203cec663bc1eabf0aaede4,6b42acb204802253acec6607ff3a9e0b,cordeiro,RJ,2018-03-30 15:36:49,2018-04-03 05:08:33,2018-04-03 15:12:19,2018-04-16 16:56:38,2018-04-27,...,2250.0,cama_mesa_banho,brusque,SC,39.96,1.0,1.0,boleto,5.0,0
96468,fffbee3b5462987e66fb49b1c5411df2,11a0e041ea6e7e21856d2689b64e7f3a,ecc3d4eb9b17d2f0865d21f2abecc51c,montes claros,MG,2018-06-19 09:27:48,2018-06-19 09:58:03,2018-06-29 13:46:00,2018-07-05 17:51:08,2018-07-23,...,5120.0,casa_construcao,salto,SP,139.88,3.0,1.0,credit_card,5.0,0
96469,fffce4705a9662cd70adb13d4a31832d,29309aa813182aaddc9b259e31b870e6,cd79b407828f02fdbba457111c38e4c4,sao paulo,SP,2017-10-23 17:07:56,2017-10-24 17:14:25,2017-10-26 15:13:14,2017-10-28 12:22:22,2017-11-10,...,9576.0,esporte_lazer,curitiba,PR,116.85,3.0,1.0,credit_card,5.0,0

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 96470 entries, 0 to 96469
Data columns (total 26 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       96470 non-null  str
 1   customer_id                    96470 non-null  str
 2   customer_unique_id             96470 non-null  str
 3   customer_city                  96470 non-null  str
 4   customer_state                 96470 non-null  str
 5   order_purchase_timestamp       96470 non-null  datetime64[us]
 6   order_approved_at              96456 non-null  datetime64[us]
 7   order_delivered_carrier_date   96469 non-null  datetime64[us]
 8   order_delivered_customer_date  96470 non-null  datetime64[us]
 9   order_estimated_delivery_date  96470 non-null  datetime64[us]
 10  number_of_items                96470 non-null  int64
 11  number_of_products             96470 non-null  int64
 12  number_of_sellers              96470 non-null  int64
 13  total_price                    96470 non-null  float64
 14  total_freight                  96470 non-null  float64
 15  total_product_weight           96454 non-null  float64
 16  total_product_volume           96454 non-null  float64
 17  product_category_name          95138 non-null  str
 18  seller_city                    96470 non-null  str
 19  seller_state                   96470 non-null  str
 20  total_payment_value            96469 non-null  float64
 21  max_payment_installments       96469 non-null  float64
 22  number_of_payments             96469 non-null  float64
 23  payment_type                   96469 non-null  str
 24  average_review_score           95824 non-null  float64
 25  is_late                        96470 non-null  int64
dtypes: datetime64[us](5), float64(8), int64(4), str(9)
memory usage: 19.1 MB

In [9]:
df.isnull().sum()

order_id                            0
customer_id                         0
customer_unique_id                  0
customer_city                       0
customer_state                      0
order_purchase_timestamp            0
order_approved_at                  14
order_delivered_carrier_date        1
order_delivered_customer_date       0
order_estimated_delivery_date       0
number_of_items                     0
number_of_products                  0
number_of_sellers                   0
total_price                         0
total_freight                       0
total_product_weight               16
total_product_volume               16
product_category_name            1332
seller_city                         0
seller_state                        0
total_payment_value                 1
max_payment_installments            1
number_of_payments                  1
payment_type                        1
average_review_score              646
is_late                             0
dtype: int64

In [10]:
df["seller_city"].unique()

<StringArray>
[          'borda da mata',                  'franca',
                  'loanda',               'sao paulo',
     'presidente prudente',             'santo andre',
                'ibitinga',   'sao jose do rio preto',
                'cascavel',               'guarulhos',
 ...
                'campanha', 'barbacena/ minas gerais',
               'barbacena',            'belford roxo',
           'guaratingueta',                 'janauba',
              'barro alto',                 'goioere',
           'belo horizont',                   'avare']
Length: 595, dtype: str

In [11]:
df["product_category_name"].unique()

<StringArray>
[                              'moveis_decoracao',
                                     'perfumaria',
                             'ferramentas_jardim',
                                      'telefonia',
                                   'beleza_saude',
                    'fashion_bolsas_e_acessorios',
                                'cama_mesa_banho',
                                  'esporte_lazer',
                                 'consoles_games',
                                     'cool_stuff',
                                      'alimentos',
                                    'eletronicos',
              'construcao_ferramentas_construcao',
                         'informatica_acessorios',
                                'livros_tecnicos',
                                          'bebes',
              'construcao_ferramentas_iluminacao',
                                     'brinquedos',
                                      'papelaria',
                          'utilidades_domesticas',
                  'industria_comercio_e_negocios',
                                       'pet_shop',
                              'moveis_escritorio',
                             'relogios_presentes',
                                     'automotivo',
                                              nan,
                               'eletrodomesticos',
 'moveis_cozinha_area_de_servico_jantar_e_jardim',
                                  'casa_conforto',
                    'portateis_casa_forno_e_cafe',
                                'fraldas_higiene',
                               'malas_acessorios',
                      'agro_industria_e_comercio',
                                          'audio',
                                   'climatizacao',
                                 'telefonia_fixa',
                        'sinalizacao_e_seguranca',
                                'eletroportateis',
                  'construcao_ferramentas_jardim',
                          'instrumentos_musicais',
                                'casa_construcao',
                         'livros_interesse_geral',
                              'artigos_de_festas',
                                          'artes',
               'construcao_ferramentas_seguranca',
                                      'cine_foto',
                 'fashion_underwear_e_moda_praia',
                              'alimentos_bebidas',
                        'fashion_roupa_masculina',
                                        'bebidas',
                                    'moveis_sala',
                                   'market_place',
                                         'musica',
                               'fashion_calcados',
                                         'flores',
                             'eletrodomesticos_2',
                         'fashion_roupa_feminina',
                                            'pcs',
                              'livros_importados',
                               'artigos_de_natal',
                                  'moveis_quarto',
  'portateis_cozinha_e_preparadores_de_alimentos',
                                'casa_conforto_2',
                                   'dvds_blu_ray',
                             'artes_e_artesanato',
                              'cds_dvds_musicais',
                      'moveis_colchao_e_estofado',
                       'tablets_impressao_imagem',
             'construcao_ferramentas_ferramentas',
                                'fashion_esporte',
                                       'pc_gamer',
                                     'la_cuisine',
                             'seguros_e_servicos',
                  'fashion_roupa_infanto_juvenil']
Length: 74, dtype: str

In [12]:
print("Rows:", len(df))
print("Unique orders:", df["order_id"].nunique())

Rows: 96470
Unique orders: 96470

In [80]:
ingested_df =  df.copy()

In [14]:
df.drop(columns=['order_id', 'customer_id', 'customer_unique_id'], inplace=True)

In [15]:
df.drop(columns=['customer_city', "order_delivered_carrier_date", "order_delivered_customer_date", "product_id", "seller_id", "seller_city", "review_score",], inplace=True)

KeyError: "['product_id', 'seller_id', 'review_score'] not found in axis"

In [ ]:
df.head()

,customer_state,order_purchase_timestamp,order_approved_at,order_estimated_delivery_date,price,freight_value,product_category_name,product_weight_g,product_length_cm,product_height_cm,product_width_cm,seller_state,payment_type,payment_installments,payment_value,is_late
0,RJ,2017-09-13 08:59:02,2017-09-13 09:45:35,2017-09-29,58.90,13.29,cool_stuff,650.0,28.0,9.0,14.0,SP,credit_card,2.0,72.19,0
1,SP,2017-04-26 10:53:06,2017-04-26 11:05:13,2017-05-15,239.90,19.93,pet_shop,30000.0,50.0,30.0,40.0,SP,credit_card,3.0,259.83,0
2,MG,2018-01-14 14:33:31,2018-01-14 14:48:30,2018-02-05,199.00,17.87,moveis_decoracao,3050.0,33.0,13.0,33.0,MG,credit_card,5.0,216.87,0
3,SP,2018-08-08 10:00:35,2018-08-08 10:10:18,2018-08-20,12.99,12.79,perfumaria,200.0,16.0,10.0,15.0,SP,credit_card,2.0,25.78,0
4,SP,2017-02-04 13:57:51,2017-02-04 14:10:13,2017-03-17,199.90,18.14,ferramentas_jardim,3750.0,35.0,40.0,30.0,PR,credit_card,3.0,218.04,0

In [29]:
ingested_df.head()

,order_id,customer_id,customer_unique_id,customer_city,customer_state,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,...,total_product_volume,product_category_name,seller_city,seller_state,total_payment_value,max_payment_installments,number_of_payments,payment_type,average_review_score,is_late
0,000229ec398224ef6ca0657da4fc703e,6489ae5e4333f3693df5ad4372dab6d3,3818d81c6709e39d06b2738a8d3a2474,para de minas,MG,2018-01-14 14:33:31,2018-01-14 14:48:30,2018-01-16 12:36:48,2018-01-22 13:19:16,2018-02-05,...,14157.0,Home & Furniture,borda da mata,MG,216.87,5.0,1.0,credit_card,5.0,0
1,00024acbcdf0a6daa1e931b038114c75,d4eb9395c8c0431ee92fce09860c5a06,af861d436cfc08b2c2ddefd0ba074622,atibaia,SP,2018-08-08 10:00:35,2018-08-08 10:10:18,2018-08-10 13:28:00,2018-08-14 13:32:39,2018-08-20,...,2400.0,Beauty & Personal Care,franca,SP,25.78,2.0,1.0,credit_card,4.0,0
2,00042b26cf59d7ce69dfabb4e55b4fd9,58dbd0b2d70206bf40e62cd34e84d795,64b576fb70d441e8f1b2d7d446e483c5,varzea paulista,SP,2017-02-04 13:57:51,2017-02-04 14:10:13,2017-02-16 09:46:09,2017-03-01 16:42:31,2017-03-17,...,42000.0,Tools & Construction,loanda,PR,218.04,3.0,1.0,credit_card,5.0,0
3,00054e8431b9d7675808bcb819fb4a32,32e2e6ab09e778d99bf2e0ecd4898718,635d9ac1680f03288e72ada3a1035803,guararapes,SP,2017-12-10 11:53:48,2017-12-10 12:10:31,2017-12-12 01:07:48,2017-12-18 22:03:38,2018-01-04,...,2700.0,Telephony,sao paulo,SP,31.75,1.0,1.0,credit_card,4.0,0
4,000576fe39319847cbb9d288c5617fa6,9ed5e522dd9dd85b4af4a077526d8117,fda4476abb6307ab3c415b7e6d026526,praia grande,SP,2018-07-04 12:08:27,2018-07-05 16:35:48,2018-07-05 12:15:00,2018-07-09 14:04:07,2018-07-25,...,118125.0,Tools & Construction,presidente prudente,SP,880.75,10.0,1.0,credit_card,5.0,0

In [ ]:
##capturing the purchase hour, purchase_day_of_week and purchase_month
df["order_purchase_hour"]= df["order_purchase_timestamp"].dt.hour

In [ ]:
df["order_purchase_day_of_week"] = df["order_purchase_timestamp"].dt.dayofweek

In [ ]:
df["order_purchase_month"]= df["order_purchase_timestamp"].dt.month

In [ ]:
df.head()

,customer_state,order_purchase_timestamp,order_approved_at,order_estimated_delivery_date,price,freight_value,product_category_name,product_weight_g,product_length_cm,product_height_cm,product_width_cm,seller_state,payment_type,payment_installments,payment_value,is_late,order_purchase_hour,order_purchase_day_of_week,order_purchase_month
0,RJ,2017-09-13 08:59:02,2017-09-13 09:45:35,2017-09-29,58.90,13.29,cool_stuff,650.0,28.0,9.0,14.0,SP,credit_card,2.0,72.19,0,8,2,9
1,SP,2017-04-26 10:53:06,2017-04-26 11:05:13,2017-05-15,239.90,19.93,pet_shop,30000.0,50.0,30.0,40.0,SP,credit_card,3.0,259.83,0,10,2,4
2,MG,2018-01-14 14:33:31,2018-01-14 14:48:30,2018-02-05,199.00,17.87,moveis_decoracao,3050.0,33.0,13.0,33.0,MG,credit_card,5.0,216.87,0,14,6,1
3,SP,2018-08-08 10:00:35,2018-08-08 10:10:18,2018-08-20,12.99,12.79,perfumaria,200.0,16.0,10.0,15.0,SP,credit_card,2.0,25.78,0,10,2,8
4,SP,2017-02-04 13:57:51,2017-02-04 14:10:13,2017-03-17,199.90,18.14,ferramentas_jardim,3750.0,35.0,40.0,30.0,PR,credit_card,3.0,218.04,0,13,5,2

In [ ]:
df["order_purchase_year"]= df["order_purchase_timestamp"].dt.year

In [ ]:
df.head()

,customer_state,order_purchase_timestamp,order_approved_at,order_estimated_delivery_date,price,freight_value,product_category_name,product_weight_g,product_length_cm,product_height_cm,product_width_cm,seller_state,payment_type,payment_installments,payment_value,is_late,order_purchase_hour,order_purchase_day_of_week,order_purchase_month,order_purchase_year
0,RJ,2017-09-13 08:59:02,2017-09-13 09:45:35,2017-09-29,58.90,13.29,cool_stuff,650.0,28.0,9.0,14.0,SP,credit_card,2.0,72.19,0,8,2,9,2017
1,SP,2017-04-26 10:53:06,2017-04-26 11:05:13,2017-05-15,239.90,19.93,pet_shop,30000.0,50.0,30.0,40.0,SP,credit_card,3.0,259.83,0,10,2,4,2017
2,MG,2018-01-14 14:33:31,2018-01-14 14:48:30,2018-02-05,199.00,17.87,moveis_decoracao,3050.0,33.0,13.0,33.0,MG,credit_card,5.0,216.87,0,14,6,1,2018
3,SP,2018-08-08 10:00:35,2018-08-08 10:10:18,2018-08-20,12.99,12.79,perfumaria,200.0,16.0,10.0,15.0,SP,credit_card,2.0,25.78,0,10,2,8,2018
4,SP,2017-02-04 13:57:51,2017-02-04 14:10:13,2017-03-17,199.90,18.14,ferramentas_jardim,3750.0,35.0,40.0,30.0,PR,credit_card,3.0,218.04,0,13,5,2,2017

In [ ]:
df["order_approval_delay_hours"] = (
    df["order_approved_at"]
    - df["order_purchase_timestamp"]
).dt.total_seconds() / 3600

In [ ]:
df.head()

,customer_state,order_purchase_timestamp,order_approved_at,order_estimated_delivery_date,price,freight_value,product_category_name,product_weight_g,product_length_cm,product_height_cm,...,seller_state,payment_type,payment_installments,payment_value,is_late,order_purchase_hour,order_purchase_day_of_week,order_purchase_month,order_purchase_year,order_approval_delay_hours
0,RJ,2017-09-13 08:59:02,2017-09-13 09:45:35,2017-09-29,58.90,13.29,cool_stuff,650.0,28.0,9.0,...,SP,credit_card,2.0,72.19,0,8,2,9,2017,0.775833
1,SP,2017-04-26 10:53:06,2017-04-26 11:05:13,2017-05-15,239.90,19.93,pet_shop,30000.0,50.0,30.0,...,SP,credit_card,3.0,259.83,0,10,2,4,2017,0.201944
2,MG,2018-01-14 14:33:31,2018-01-14 14:48:30,2018-02-05,199.00,17.87,moveis_decoracao,3050.0,33.0,13.0,...,MG,credit_card,5.0,216.87,0,14,6,1,2018,0.249722
3,SP,2018-08-08 10:00:35,2018-08-08 10:10:18,2018-08-20,12.99,12.79,perfumaria,200.0,16.0,10.0,...,SP,credit_card,2.0,25.78,0,10,2,8,2018,0.161944
4,SP,2017-02-04 13:57:51,2017-02-04 14:10:13,2017-03-17,199.90,18.14,ferramentas_jardim,3750.0,35.0,40.0,...,PR,credit_card,3.0,218.04,0,13,5,2,2017,0.206111

In [ ]:
df["estimated_delivery_days"] = (
    df["order_estimated_delivery_date"]
    - df["order_purchase_timestamp"]
).dt.total_seconds() / 86400

In [ ]:
df.head()

,customer_state,order_purchase_timestamp,order_approved_at,order_estimated_delivery_date,price,freight_value,product_category_name,product_weight_g,product_length_cm,product_height_cm,...,payment_type,payment_installments,payment_value,is_late,order_purchase_hour,order_purchase_day_of_week,order_purchase_month,order_purchase_year,order_approval_delay_hours,estimated_delivery_days
0,RJ,2017-09-13 08:59:02,2017-09-13 09:45:35,2017-09-29,58.90,13.29,cool_stuff,650.0,28.0,9.0,...,credit_card,2.0,72.19,0,8,2,9,2017,0.775833,15.625671
1,SP,2017-04-26 10:53:06,2017-04-26 11:05:13,2017-05-15,239.90,19.93,pet_shop,30000.0,50.0,30.0,...,credit_card,3.0,259.83,0,10,2,4,2017,0.201944,18.546458
2,MG,2018-01-14 14:33:31,2018-01-14 14:48:30,2018-02-05,199.00,17.87,moveis_decoracao,3050.0,33.0,13.0,...,credit_card,5.0,216.87,0,14,6,1,2018,0.249722,21.393391
3,SP,2018-08-08 10:00:35,2018-08-08 10:10:18,2018-08-20,12.99,12.79,perfumaria,200.0,16.0,10.0,...,credit_card,2.0,25.78,0,10,2,8,2018,0.161944,11.582928
4,SP,2017-02-04 13:57:51,2017-02-04 14:10:13,2017-03-17,199.90,18.14,ferramentas_jardim,3750.0,35.0,40.0,...,credit_card,3.0,218.04,0,13,5,2,2017,0.206111,40.418160

In [ ]:
df["estimated_delivery_days_after_approval"] = (
    df["order_estimated_delivery_date"]
    - df["order_approved_at"]
).dt.total_seconds() / 86400

In [ ]:
df.drop(columns=["order_purchase_timestamp", 'order_approved_at','order_estimated_delivery_date' ], inplace= True)

In [ ]:
df.head()

,customer_state,price,freight_value,product_category_name,product_weight_g,product_length_cm,product_height_cm,product_width_cm,seller_state,payment_type,payment_installments,payment_value,is_late,order_purchase_hour,order_purchase_day_of_week,order_purchase_month,order_purchase_year,order_approval_delay_hours,estimated_delivery_days,estimated_delivery_days_after_approval
0,RJ,58.90,13.29,cool_stuff,650.0,28.0,9.0,14.0,SP,credit_card,2.0,72.19,0,8,2,9,2017,0.775833,15.625671,15.593345
1,SP,239.90,19.93,pet_shop,30000.0,50.0,30.0,40.0,SP,credit_card,3.0,259.83,0,10,2,4,2017,0.201944,18.546458,18.538044
2,MG,199.00,17.87,moveis_decoracao,3050.0,33.0,13.0,33.0,MG,credit_card,5.0,216.87,0,14,6,1,2018,0.249722,21.393391,21.382986
3,SP,12.99,12.79,perfumaria,200.0,16.0,10.0,15.0,SP,credit_card,2.0,25.78,0,10,2,8,2018,0.161944,11.582928,11.576181
4,SP,199.90,18.14,ferramentas_jardim,3750.0,35.0,40.0,30.0,PR,credit_card,3.0,218.04,0,13,5,2,2017,0.206111,40.418160,40.409572

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 115715 entries, 0 to 115714
Data columns (total 20 columns):
 #   Column                                  Non-Null Count   Dtype
---  ------                                  --------------   -----
 0   customer_state                          115715 non-null  str
 1   price                                   115715 non-null  float64
 2   freight_value                           115715 non-null  float64
 3   product_category_name                   114077 non-null  str
 4   product_weight_g                        115695 non-null  float64
 5   product_length_cm                       115695 non-null  float64
 6   product_height_cm                       115695 non-null  float64
 7   product_width_cm                        115695 non-null  float64
 8   seller_state                            115715 non-null  str
 9   payment_type                            115712 non-null  str
 10  payment_installments                    115712 non-null  float64
 11  payment_value                           115712 non-null  float64
 12  is_late                                 115715 non-null  int64
 13  order_purchase_hour                     115715 non-null  int32
 14  order_purchase_day_of_week              115715 non-null  int32
 15  order_purchase_month                    115715 non-null  int32
 16  order_purchase_year                     115715 non-null  int32
 17  order_approval_delay_hours              115700 non-null  float64
 18  estimated_delivery_days                 115715 non-null  float64
 19  estimated_delivery_days_after_approval  115700 non-null  float64
dtypes: float64(11), int32(4), int64(1), str(4)
memory usage: 15.9 MB

In [ ]:
ingested_df.head()

,order_id,customer_id,customer_unique_id,customer_city,customer_state,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,...,product_length_cm,product_height_cm,product_width_cm,seller_city,seller_state,payment_type,payment_installments,payment_value,review_score,is_late
0,00010242fe8c5a6d1ba2dd792cb16214,3ce436f183e68e07877b285a838db11a,871766c5855e863f6eccc05f988b23cb,campos dos goytacazes,RJ,2017-09-13 08:59:02,2017-09-13 09:45:35,2017-09-19 18:34:16,2017-09-20 23:43:48,2017-09-29,...,28.0,9.0,14.0,volta redonda,SP,credit_card,2.0,72.19,5.0,0
1,00018f77f2f0320c557190d7a144bdd3,f6dd3ec061db4e3987629fe6b26e5cce,eb28e67c4c0b83846050ddfb8a35d051,santa fe do sul,SP,2017-04-26 10:53:06,2017-04-26 11:05:13,2017-05-04 14:35:00,2017-05-12 16:04:24,2017-05-15,...,50.0,30.0,40.0,sao paulo,SP,credit_card,3.0,259.83,4.0,0
2,000229ec398224ef6ca0657da4fc703e,6489ae5e4333f3693df5ad4372dab6d3,3818d81c6709e39d06b2738a8d3a2474,para de minas,MG,2018-01-14 14:33:31,2018-01-14 14:48:30,2018-01-16 12:36:48,2018-01-22 13:19:16,2018-02-05,...,33.0,13.0,33.0,borda da mata,MG,credit_card,5.0,216.87,5.0,0
3,00024acbcdf0a6daa1e931b038114c75,d4eb9395c8c0431ee92fce09860c5a06,af861d436cfc08b2c2ddefd0ba074622,atibaia,SP,2018-08-08 10:00:35,2018-08-08 10:10:18,2018-08-10 13:28:00,2018-08-14 13:32:39,2018-08-20,...,16.0,10.0,15.0,franca,SP,credit_card,2.0,25.78,4.0,0
4,00042b26cf59d7ce69dfabb4e55b4fd9,58dbd0b2d70206bf40e62cd34e84d795,64b576fb70d441e8f1b2d7d446e483c5,varzea paulista,SP,2017-02-04 13:57:51,2017-02-04 14:10:13,2017-02-16 09:46:09,2017-03-01 16:42:31,2017-03-17,...,35.0,40.0,30.0,loanda,PR,credit_card,3.0,218.04,5.0,0

In [ ]:
order_df = (
    ingested_df.groupby("order_id")
    .agg(
        customer_state=("customer_state", "first"),

        price=("price", "sum"),
        freight_value=("freight_value", "sum"),

        product_weight_g=("product_weight_g", "sum"),

        payment_installments=("payment_installments", "max"),
        payment_value=("payment_value", "first"),

        seller_state=("seller_state", "first"),

        order_purchase_timestamp=(
            "order_purchase_timestamp", "first"
        ),

        order_approved_at=(
            "order_approved_at", "first"
        ),

        order_estimated_delivery_date=(
            "order_estimated_delivery_date", "first"
        ),

        order_delivered_customer_date=(
            "order_delivered_customer_date", "first"
        ),

        is_late=("is_late", "first"),

        number_of_items=("order_id", "size"),

        number_of_sellers=("seller_id", "nunique"),

        product_category_name=(
            "product_category_name", "first"
        )
    )
    .reset_index()
)

In [ ]:
order_df.head()

,order_id,customer_state,price,freight_value,product_weight_g,payment_installments,payment_value,seller_state,order_purchase_timestamp,order_approved_at,order_estimated_delivery_date,order_delivered_customer_date,is_late,number_of_items,number_of_sellers,product_category_name
0,00010242fe8c5a6d1ba2dd792cb16214,RJ,58.90,13.29,650.0,2.0,72.19,SP,2017-09-13 08:59:02,2017-09-13 09:45:35,2017-09-29,2017-09-20 23:43:48,0,1,1,cool_stuff
1,00018f77f2f0320c557190d7a144bdd3,SP,239.90,19.93,30000.0,3.0,259.83,SP,2017-04-26 10:53:06,2017-04-26 11:05:13,2017-05-15,2017-05-12 16:04:24,0,1,1,pet_shop
2,000229ec398224ef6ca0657da4fc703e,MG,199.00,17.87,3050.0,5.0,216.87,MG,2018-01-14 14:33:31,2018-01-14 14:48:30,2018-02-05,2018-01-22 13:19:16,0,1,1,moveis_decoracao
3,00024acbcdf0a6daa1e931b038114c75,SP,12.99,12.79,200.0,2.0,25.78,SP,2018-08-08 10:00:35,2018-08-08 10:10:18,2018-08-20,2018-08-14 13:32:39,0,1,1,perfumaria
4,00042b26cf59d7ce69dfabb4e55b4fd9,SP,199.90,18.14,3750.0,3.0,218.04,PR,2017-02-04 13:57:51,2017-02-04 14:10:13,2017-03-17,2017-03-01 16:42:31,0,1,1,ferramentas_jardim

In [ ]:
print(order_df.shape)
print(order_df["order_id"].nunique())

(96470, 16)
96470

In [ ]:
ingested_df[ingested_df["order_id"].duplicated()]

,order_id,customer_id,customer_unique_id,customer_city,customer_state,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,...,product_length_cm,product_height_cm,product_width_cm,seller_city,seller_state,payment_type,payment_installments,payment_value,review_score,is_late
14,0008288aa423d2a3f00fcb17cd7d8719,2355af7c75e7c98b43a87b2a7f210dc5,9e4159995424971423b98c4a8bc11529,jandira,SP,2018-02-13 22:10:21,2018-02-15 03:55:52,2018-02-20 18:23:28,2018-02-26 13:55:22,2018-03-06,...,30.0,22.0,30.0,sao jose do rio preto,SP,boleto,1.0,126.54,5.0,0
33,00143d0f86d6fbd9f9b38ab440ac16f5,2e45292979b9b2700ea09560eeb0f803,bb8a37225e0279ac8a274c9765617eaf,goiania,GO,2017-10-16 15:29:43,2017-10-16 16:07:52,2017-10-16 23:04:43,2017-10-27 18:43:56,2017-11-06,...,17.0,11.0,14.0,sorocaba,SP,credit_card,1.0,109.29,NaN,0
34,00143d0f86d6fbd9f9b38ab440ac16f5,2e45292979b9b2700ea09560eeb0f803,bb8a37225e0279ac8a274c9765617eaf,goiania,GO,2017-10-16 15:29:43,2017-10-16 16:07:52,2017-10-16 23:04:43,2017-10-27 18:43:56,2017-11-06,...,17.0,11.0,14.0,sorocaba,SP,credit_card,1.0,109.29,NaN,0
39,0016dfedd97fc2950e388d2971d718c7,2c8b917c5d7dd720ebe36a5ed3b501ec,33febb33a42a35f5826a22584b127f9d,canavieiras,BA,2017-04-28 19:54:40,2017-04-29 10:05:12,2017-05-16 08:40:49,2017-05-22 18:32:21,2017-06-01,...,27.0,6.0,23.0,sao paulo,SP,voucher,1.0,17.92,5.0,0
44,001ab0a7578dd66cd4b0a71f5b6e1e41,8bb3bef4e75a95524235cdc11a7331af,d1f24d1d504e27bee13b415e40daeab0,salvador,BA,2017-12-27 00:38:47,2017-12-28 02:33:42,2017-12-28 18:09:35,2018-01-17 20:43:29,2018-01-29,...,22.0,13.0,15.0,brasilia,DF,boleto,1.0,127.56,4.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115671,fffb9224b6fc7c43ebb0904318b10b5f,4d3abb73ceb86353aeadbe698aa9d5cb,f736308cd9952b33b90b9fe94da9c8f5,serra talhada,PE,2017-10-27 16:51:00,2017-10-28 02:55:58,2017-11-10 19:31:52,2017-11-17 19:41:42,2017-11-27,...,16.0,14.0,11.0,sao goncalo,RJ,boleto,1.0,356.76,4.0,0
115672,fffb9224b6fc7c43ebb0904318b10b5f,4d3abb73ceb86353aeadbe698aa9d5cb,f736308cd9952b33b90b9fe94da9c8f5,serra talhada,PE,2017-10-27 16:51:00,2017-10-28 02:55:58,2017-11-10 19:31:52,2017-11-17 19:41:42,2017-11-27,...,16.0,14.0,11.0,sao goncalo,RJ,boleto,1.0,356.76,4.0,0
115673,fffb9224b6fc7c43ebb0904318b10b5f,4d3abb73ceb86353aeadbe698aa9d5cb,f736308cd9952b33b90b9fe94da9c8f5,serra talhada,PE,2017-10-27 16:51:00,2017-10-28 02:55:58,2017-11-10 19:31:52,2017-11-17 19:41:42,2017-11-27,...,16.0,14.0,11.0,sao goncalo,RJ,boleto,1.0,356.76,4.0,0
115685,ff4935343715e7a6dae3e550f73a6459,8bbd68396f2112f979111bfdd363e286,e35b2a3c980b6e0fc66c66b8e1122e93,pedregulho,SP,2017-10-10 15:41:10,2017-10-12 02:29:16,2017-10-16 20:57:40,2017-10-23 18:43:06,2017-11-13,...,33.0,20.0,15.0,sarandi,PR,boleto,1.0,633.50,4.0,0
115710,ff632bc583a94f23c59db4cbaa0ba2ab,0214d81e1cb90cf47f40f5345a1a6c08,3eb2432c10c27f0444e15779fb248c88,santos,SP,2018-05-09 22:23:41,2018-05-09 22:53:41,2018-05-10 19:05:00,2018-05-21 19:03:44,2018-05-17,...,22.0,3.0,15.0,hortolandia,SP,credit_card,1.0,236.56,5.0,1

In [ ]:
ingested_df.duplicated().sum()

np.int64(11427)

In [ ]:
order_counts = (
    ingested_df["order_id"]
    .value_counts()
)
print(order_counts)
print(order_counts.describe())

order_id
895ab968e7bb0d5659d16cd74cd1650c    63
fedcd9f7ccdc8cba3a18defedd1a5547    38
ccf804e764ed5650cd8759557269dc13    26
465c2e1bee4561cb39e0db8c5993aafc    24
68986e4324f6a21481df4e6e89abcf01    24
                                    ..
ff61c865c1495e71465c79009005611c     1
ff6373dfa00603bd092cb8f6eef3349a     1
ff63c818e5e38bb25ec5abce62d83d4f     1
ff646f0b1571ec3bb3b46ddecce4d991     1
ff64e0ba4800eb1127ac32aeac2b51f9     1
Name: count, Length: 96470, dtype: int64
count    96470.000000
mean         1.199492
std          0.749613
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max         63.000000
Name: count, dtype: float64

In [ ]:
order_counts.value_counts().sort_index()

count
1     83796
2      9631
3      1536
4       816
5       238
6       273
7        47
8        40
9        12
10       15
11       11
12       21
13        4
14        5
15        6
16        2
19        1
20        3
21        3
22        2
24        5
26        1
38        1
63        1
Name: count, dtype: int64

:

In [ ]:
ingested_df[ingested_df.duplicated()]

,order_id,customer_id,customer_unique_id,customer_city,customer_state,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,...,product_length_cm,product_height_cm,product_width_cm,seller_city,seller_state,payment_type,payment_installments,payment_value,review_score,is_late
28,002c9def9c9b951b1bec6d50753c9891,06cf02bf583b05fd91bc8eec0f1b4c3f,6bcc1cd0c7f8bffa6f67a6a1fbef5782,sao paulo,SP,2018-05-14 16:57:47,2018-05-15 17:37:51,2018-05-17 13:27:00,2018-05-18 14:37:38,2018-05-25,...,25.0,10.0,36.0,guarulhos,SP,credit_card,1.0,173.80,4.0,0
38,003324c70b19a16798817b2b3640e721,43696894b5bf8fbe1a40b2148ea505a0,fbe6316a06058c651539cbf59ec5a0ef,diamantina,MG,2017-05-18 19:04:48,2017-05-18 19:22:34,2017-05-19 16:04:55,2017-05-30 08:12:15,2017-06-07,...,33.0,10.0,49.0,borda da mata,MG,credit_card,5.0,234.70,1.0,0
46,0035246a40f520710769010f752e7507,4bcf2ad7ccc061c13ff360aae5b7abcd,d56ded4569dd9821b2f83710a56afbde,sao paulo,SP,2017-08-17 00:57:23,2017-08-17 01:25:39,2017-08-22 15:33:53,2017-08-28 19:14:03,2017-09-06,...,45.0,15.0,35.0,ibitinga,SP,credit_card,8.0,99.11,5.0,0
63,008d9bf350ff02ed444b3452cf3f57e0,84f30d2805ae1bddbe5deefc84c80cd0,0511b00dba27c937d7c1b15aa385359e,vila velha,ES,2018-06-04 08:57:02,2018-06-04 09:11:48,2018-06-04 12:19:00,2018-06-13 19:24:52,2018-07-11,...,18.0,12.0,13.0,sao paulo,SP,credit_card,1.0,50.44,5.0,0
88,009905140e9f8cc35d5be897937381db,c5452f24faa0b6d0febc5ec4ea9e3b13,55c30000d759e95fa8d94da28ecd3288,goiania,GO,2018-03-15 12:33:45,2018-03-15 12:49:18,2018-03-16 17:12:25,2018-03-28 20:44:41,2018-04-11,...,25.0,8.0,19.0,ibitinga,SP,credit_card,10.0,116.44,5.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115701,ff1f8f328e5a59ac754240b6dd31bcb4,ba53e87622e90e0a905d871c0c8d53af,0cd33e5cc45d8be1415bf478ead300f5,guaruja,SP,2017-08-10 16:07:21,2017-08-10 16:25:17,2017-08-14 20:59:59,2017-08-19 14:17:43,2017-08-30,...,45.0,15.0,35.0,ibitinga,SP,voucher,1.0,78.28,5.0,0
115702,ff1f8f328e5a59ac754240b6dd31bcb4,ba53e87622e90e0a905d871c0c8d53af,0cd33e5cc45d8be1415bf478ead300f5,guaruja,SP,2017-08-10 16:07:21,2017-08-10 16:25:17,2017-08-14 20:59:59,2017-08-19 14:17:43,2017-08-30,...,45.0,15.0,35.0,ibitinga,SP,voucher,1.0,26.03,5.0,0
115703,ff1f8f328e5a59ac754240b6dd31bcb4,ba53e87622e90e0a905d871c0c8d53af,0cd33e5cc45d8be1415bf478ead300f5,guaruja,SP,2017-08-10 16:07:21,2017-08-10 16:25:17,2017-08-14 20:59:59,2017-08-19 14:17:43,2017-08-30,...,45.0,15.0,35.0,ibitinga,SP,voucher,1.0,142.58,5.0,0
115704,ff1f8f328e5a59ac754240b6dd31bcb4,ba53e87622e90e0a905d871c0c8d53af,0cd33e5cc45d8be1415bf478ead300f5,guaruja,SP,2017-08-10 16:07:21,2017-08-10 16:25:17,2017-08-14 20:59:59,2017-08-19 14:17:43,2017-08-30,...,45.0,15.0,35.0,ibitinga,SP,credit_card,1.0,11.17,5.0,0
115705,ff1f8f328e5a59ac754240b6dd31bcb4,ba53e87622e90e0a905d871c0c8d53af,0cd33e5cc45d8be1415bf478ead300f5,guaruja,SP,2017-08-10 16:07:21,2017-08-10 16:25:17,2017-08-14 20:59:59,2017-08-19 14:17:43,2017-08-30,...,45.0,15.0,35.0,ibitinga,SP,voucher,1.0,78.28,5.0,0

In [ ]:
print(ingested_df.duplicated().sum())

11427

In [ ]:
import numpy as np
ingested_df.iloc[np.where(ingested_df.order_id=="ff1f8f328e5a59ac754240b6dd31bcb4")[0]]

,order_id,customer_id,customer_unique_id,customer_city,customer_state,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,...,product_length_cm,product_height_cm,product_width_cm,seller_city,seller_state,payment_type,payment_installments,payment_value,review_score,is_late
115694,ff1f8f328e5a59ac754240b6dd31bcb4,ba53e87622e90e0a905d871c0c8d53af,0cd33e5cc45d8be1415bf478ead300f5,guaruja,SP,2017-08-10 16:07:21,2017-08-10 16:25:17,2017-08-14 20:59:59,2017-08-19 14:17:43,2017-08-30,...,45.0,15.0,35.0,ibitinga,SP,voucher,1.0,26.03,5.0,0
115695,ff1f8f328e5a59ac754240b6dd31bcb4,ba53e87622e90e0a905d871c0c8d53af,0cd33e5cc45d8be1415bf478ead300f5,guaruja,SP,2017-08-10 16:07:21,2017-08-10 16:25:17,2017-08-14 20:59:59,2017-08-19 14:17:43,2017-08-30,...,45.0,15.0,35.0,ibitinga,SP,voucher,1.0,142.58,5.0,0
115696,ff1f8f328e5a59ac754240b6dd31bcb4,ba53e87622e90e0a905d871c0c8d53af,0cd33e5cc45d8be1415bf478ead300f5,guaruja,SP,2017-08-10 16:07:21,2017-08-10 16:25:17,2017-08-14 20:59:59,2017-08-19 14:17:43,2017-08-30,...,45.0,15.0,35.0,ibitinga,SP,credit_card,1.0,11.17,5.0,0
115697,ff1f8f328e5a59ac754240b6dd31bcb4,ba53e87622e90e0a905d871c0c8d53af,0cd33e5cc45d8be1415bf478ead300f5,guaruja,SP,2017-08-10 16:07:21,2017-08-10 16:25:17,2017-08-14 20:59:59,2017-08-19 14:17:43,2017-08-30,...,45.0,15.0,35.0,ibitinga,SP,voucher,1.0,78.28,5.0,0
115698,ff1f8f328e5a59ac754240b6dd31bcb4,ba53e87622e90e0a905d871c0c8d53af,0cd33e5cc45d8be1415bf478ead300f5,guaruja,SP,2017-08-10 16:07:21,2017-08-10 16:25:17,2017-08-14 20:59:59,2017-08-19 14:17:43,2017-08-30,...,45.0,15.0,35.0,ibitinga,SP,voucher,1.0,26.03,5.0,0
115699,ff1f8f328e5a59ac754240b6dd31bcb4,ba53e87622e90e0a905d871c0c8d53af,0cd33e5cc45d8be1415bf478ead300f5,guaruja,SP,2017-08-10 16:07:21,2017-08-10 16:25:17,2017-08-14 20:59:59,2017-08-19 14:17:43,2017-08-30,...,45.0,15.0,35.0,ibitinga,SP,voucher,1.0,142.58,5.0,0
115700,ff1f8f328e5a59ac754240b6dd31bcb4,ba53e87622e90e0a905d871c0c8d53af,0cd33e5cc45d8be1415bf478ead300f5,guaruja,SP,2017-08-10 16:07:21,2017-08-10 16:25:17,2017-08-14 20:59:59,2017-08-19 14:17:43,2017-08-30,...,45.0,15.0,35.0,ibitinga,SP,credit_card,1.0,11.17,5.0,0
115701,ff1f8f328e5a59ac754240b6dd31bcb4,ba53e87622e90e0a905d871c0c8d53af,0cd33e5cc45d8be1415bf478ead300f5,guaruja,SP,2017-08-10 16:07:21,2017-08-10 16:25:17,2017-08-14 20:59:59,2017-08-19 14:17:43,2017-08-30,...,45.0,15.0,35.0,ibitinga,SP,voucher,1.0,78.28,5.0,0
115702,ff1f8f328e5a59ac754240b6dd31bcb4,ba53e87622e90e0a905d871c0c8d53af,0cd33e5cc45d8be1415bf478ead300f5,guaruja,SP,2017-08-10 16:07:21,2017-08-10 16:25:17,2017-08-14 20:59:59,2017-08-19 14:17:43,2017-08-30,...,45.0,15.0,35.0,ibitinga,SP,voucher,1.0,26.03,5.0,0
115703,ff1f8f328e5a59ac754240b6dd31bcb4,ba53e87622e90e0a905d871c0c8d53af,0cd33e5cc45d8be1415bf478ead300f5,guaruja,SP,2017-08-10 16:07:21,2017-08-10 16:25:17,2017-08-14 20:59:59,2017-08-19 14:17:43,2017-08-30,...,45.0,15.0,35.0,ibitinga,SP,voucher,1.0,142.58,5.0,0
115704,ff1f8f328e5a59ac754240b6dd31bcb4,ba53e87622e90e0a905d871c0c8d53af,0cd33e5cc45d8be1415bf478ead300f5,guaruja,SP,2017-08-10 16:07:21,2017-08-10 16:25:17,2017-08-14 20:59:59,2017-08-19 14:17:43,2017-08-30,...,45.0,15.0,35.0,ibitinga,SP,credit_card,1.0,11.17,5.0,0
115705,ff1f8f328e5a59ac754240b6dd31bcb4,ba53e87622e90e0a905d871c0c8d53af,0cd33e5cc45d8be1415bf478ead300f5,guaruja,SP,2017-08-10 16:07:21,2017-08-10 16:25:17,2017-08-14 20:59:59,2017-08-19 14:17:43,2017-08-30,...,45.0,15.0,35.0,ibitinga,SP,voucher,1.0,78.28,5.0,0

In [ ]:
ingested_df[["product_id", "customer_id", "order_id"]].duplicated().sum()

np.int64(15527)

In [ ]:
ingested_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 115715 entries, 0 to 115714
Data columns (total 26 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       115715 non-null  str
 1   customer_id                    115715 non-null  str
 2   customer_unique_id             115715 non-null  str
 3   customer_city                  115715 non-null  str
 4   customer_state                 115715 non-null  str
 5   order_purchase_timestamp       115715 non-null  datetime64[us]
 6   order_approved_at              115700 non-null  datetime64[us]
 7   order_delivered_carrier_date   115714 non-null  datetime64[us]
 8   order_delivered_customer_date  115715 non-null  datetime64[us]
 9   order_estimated_delivery_date  115715 non-null  datetime64[us]
 10  product_id                     115715 non-null  str
 11  seller_id                      115715 non-null  str
 12  price                          115715 non-null  float64
 13  freight_value                  115715 non-null  float64
 14  product_category_name          114077 non-null  str
 15  product_weight_g               115695 non-null  float64
 16  product_length_cm              115695 non-null  float64
 17  product_height_cm              115695 non-null  float64
 18  product_width_cm               115695 non-null  float64
 19  seller_city                    115715 non-null  str
 20  seller_state                   115715 non-null  str
 21  payment_type                   115712 non-null  str
 22  payment_installments           115712 non-null  float64
 23  payment_value                  115712 non-null  float64
 24  review_score                   114854 non-null  float64
 25  is_late                        115715 non-null  int64
dtypes: datetime64[us](5), float64(9), int64(1), str(11)
memory usage: 23.0 MB

In [ ]:
ingested_df = (
    ingested_df
    .drop_duplicates()
    .reset_index(drop=True)
)

In [ ]:
print("Rows:", len(ingested_df))
print("Unique orders:", ingested_df["order_id"].nunique())

Rows: 104288
Unique orders: 96470

In [ ]:
ingested_df.groupby("order_id").agg(
    
)

In [ ]:
ingested_df.groupby("order_id")["customer_state"].nunique().max()

np.int64(1)

In [ ]:
cols = [
    "customer_id",
    "customer_unique_id",
    "customer_state",
    "customer_city",
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_customer_date",
    "order_estimated_delivery_date",
    "is_late"
]

for col in cols:
    max_unique = (
        ingested_df
        .groupby("order_id")[col]
        .nunique()
        .max()
    )

    print(col, max_unique)

customer_id 1
customer_unique_id 1
customer_state 1
customer_city 1
order_purchase_timestamp 1
order_approved_at 1
order_delivered_customer_date 1
order_estimated_delivery_date 1
is_late 1

In [ ]:
ingested_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 104288 entries, 0 to 104287
Data columns (total 26 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       104288 non-null  str
 1   customer_id                    104288 non-null  str
 2   customer_unique_id             104288 non-null  str
 3   customer_city                  104288 non-null  str
 4   customer_state                 104288 non-null  str
 5   order_purchase_timestamp       104288 non-null  datetime64[us]
 6   order_approved_at              104274 non-null  datetime64[us]
 7   order_delivered_carrier_date   104287 non-null  datetime64[us]
 8   order_delivered_customer_date  104288 non-null  datetime64[us]
 9   order_estimated_delivery_date  104288 non-null  datetime64[us]
 10  product_id                     104288 non-null  str
 11  seller_id                      104288 non-null  str
 12  price                          104288 non-null  float64
 13  freight_value                  104288 non-null  float64
 14  product_category_name          102823 non-null  str
 15  product_weight_g               104271 non-null  float64
 16  product_length_cm              104271 non-null  float64
 17  product_height_cm              104271 non-null  float64
 18  product_width_cm               104271 non-null  float64
 19  seller_city                    104288 non-null  str
 20  seller_state                   104288 non-null  str
 21  payment_type                   104287 non-null  str
 22  payment_installments           104287 non-null  float64
 23  payment_value                  104287 non-null  float64
 24  review_score                   103566 non-null  float64
 25  is_late                        104288 non-null  int64
dtypes: datetime64[us](5), float64(9), int64(1), str(11)
memory usage: 20.7 MB

In [ ]:
"""order_df = (
    ingested_df.groupby("order_id")
    .agg(
        customer_state=("customer_state", "first"),

        price=("price", "sum"),
        freight_value=("freight_value", "sum"),

        product_weight_g=("product_weight_g", "sum"),

        payment_installments=("payment_installments", "max"),
        payment_value=("payment_value", "first"),

        seller_state=("seller_state", "first"),

        order_purchase_timestamp=(
            "order_purchase_timestamp", "first"
        ),

        order_approved_at=(
            "order_approved_at", "first"
        ),

        order_estimated_delivery_date=(
            "order_estimated_delivery_date", "first"
        ),

        order_delivered_customer_date=(
            "order_delivered_customer_date", "first"
        ),

        is_late=("is_late", "first"),

        number_of_items=("order_id", "size"),

        number_of_sellers=("seller_id", "nunique"),

        product_category_name=(
            "product_category_name", "first"
        )
    )
    .reset_index()
)"""

In [16]:
ingested_df.head()

,order_id,customer_id,customer_unique_id,customer_city,customer_state,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,...,total_product_volume,product_category_name,seller_city,seller_state,total_payment_value,max_payment_installments,number_of_payments,payment_type,average_review_score,is_late
0,000229ec398224ef6ca0657da4fc703e,6489ae5e4333f3693df5ad4372dab6d3,3818d81c6709e39d06b2738a8d3a2474,para de minas,MG,2018-01-14 14:33:31,2018-01-14 14:48:30,2018-01-16 12:36:48,2018-01-22 13:19:16,2018-02-05,...,14157.0,moveis_decoracao,borda da mata,MG,216.87,5.0,1.0,credit_card,5.0,0
1,00024acbcdf0a6daa1e931b038114c75,d4eb9395c8c0431ee92fce09860c5a06,af861d436cfc08b2c2ddefd0ba074622,atibaia,SP,2018-08-08 10:00:35,2018-08-08 10:10:18,2018-08-10 13:28:00,2018-08-14 13:32:39,2018-08-20,...,2400.0,perfumaria,franca,SP,25.78,2.0,1.0,credit_card,4.0,0
2,00042b26cf59d7ce69dfabb4e55b4fd9,58dbd0b2d70206bf40e62cd34e84d795,64b576fb70d441e8f1b2d7d446e483c5,varzea paulista,SP,2017-02-04 13:57:51,2017-02-04 14:10:13,2017-02-16 09:46:09,2017-03-01 16:42:31,2017-03-17,...,42000.0,ferramentas_jardim,loanda,PR,218.04,3.0,1.0,credit_card,5.0,0
3,00054e8431b9d7675808bcb819fb4a32,32e2e6ab09e778d99bf2e0ecd4898718,635d9ac1680f03288e72ada3a1035803,guararapes,SP,2017-12-10 11:53:48,2017-12-10 12:10:31,2017-12-12 01:07:48,2017-12-18 22:03:38,2018-01-04,...,2700.0,telefonia,sao paulo,SP,31.75,1.0,1.0,credit_card,4.0,0
4,000576fe39319847cbb9d288c5617fa6,9ed5e522dd9dd85b4af4a077526d8117,fda4476abb6307ab3c415b7e6d026526,praia grande,SP,2018-07-04 12:08:27,2018-07-05 16:35:48,2018-07-05 12:15:00,2018-07-09 14:04:07,2018-07-25,...,118125.0,ferramentas_jardim,presidente prudente,SP,880.75,10.0,1.0,credit_card,5.0,0

In [19]:
ingested_df.is_late.value_counts()

is_late
0    88644
1     7826
Name: count, dtype: int64

In [21]:
ingested_df.product_category_name.unique()

<StringArray>
[                              'moveis_decoracao',
                                     'perfumaria',
                             'ferramentas_jardim',
                                      'telefonia',
                                   'beleza_saude',
                    'fashion_bolsas_e_acessorios',
                                'cama_mesa_banho',
                                  'esporte_lazer',
                                 'consoles_games',
                                     'cool_stuff',
                                      'alimentos',
                                    'eletronicos',
              'construcao_ferramentas_construcao',
                         'informatica_acessorios',
                                'livros_tecnicos',
                                          'bebes',
              'construcao_ferramentas_iluminacao',
                                     'brinquedos',
                                      'papelaria',
                          'utilidades_domesticas',
                  'industria_comercio_e_negocios',
                                       'pet_shop',
                              'moveis_escritorio',
                             'relogios_presentes',
                                     'automotivo',
                                              nan,
                               'eletrodomesticos',
 'moveis_cozinha_area_de_servico_jantar_e_jardim',
                                  'casa_conforto',
                    'portateis_casa_forno_e_cafe',
                                'fraldas_higiene',
                               'malas_acessorios',
                      'agro_industria_e_comercio',
                                          'audio',
                                   'climatizacao',
                                 'telefonia_fixa',
                        'sinalizacao_e_seguranca',
                                'eletroportateis',
                  'construcao_ferramentas_jardim',
                          'instrumentos_musicais',
                                'casa_construcao',
                         'livros_interesse_geral',
                              'artigos_de_festas',
                                          'artes',
               'construcao_ferramentas_seguranca',
                                      'cine_foto',
                 'fashion_underwear_e_moda_praia',
                              'alimentos_bebidas',
                        'fashion_roupa_masculina',
                                        'bebidas',
                                    'moveis_sala',
                                   'market_place',
                                         'musica',
                               'fashion_calcados',
                                         'flores',
                             'eletrodomesticos_2',
                         'fashion_roupa_feminina',
                                            'pcs',
                              'livros_importados',
                               'artigos_de_natal',
                                  'moveis_quarto',
  'portateis_cozinha_e_preparadores_de_alimentos',
                                'casa_conforto_2',
                                   'dvds_blu_ray',
                             'artes_e_artesanato',
                              'cds_dvds_musicais',
                      'moveis_colchao_e_estofado',
                       'tablets_impressao_imagem',
             'construcao_ferramentas_ferramentas',
                                'fashion_esporte',
                                       'pc_gamer',
                                     'la_cuisine',
                             'seguros_e_servicos',
                  'fashion_roupa_infanto_juvenil']
Length: 74, dtype: str

In [25]:
category_mapping = {

    # 1. Home & Furniture
    "moveis_decoracao": "Home & Furniture",
    "cama_mesa_banho": "Home & Furniture",
    "utilidades_domesticas": "Home & Furniture",
    "moveis_escritorio": "Home & Furniture",
    "moveis_cozinha_area_de_servico_jantar_e_jardim": "Home & Furniture",
    "casa_conforto": "Home & Furniture",
    "moveis_sala": "Home & Furniture",
    "moveis_quarto": "Home & Furniture",
    "casa_conforto_2": "Home & Furniture",
    "moveis_colchao_e_estofado": "Home & Furniture",

    # 2. Home Appliances
    "eletrodomesticos": "Home Appliances",
    "portateis_casa_forno_e_cafe": "Home Appliances",
    "eletroportateis": "Home Appliances",
    "eletrodomesticos_2": "Home Appliances",
    "portateis_cozinha_e_preparadores_de_alimentos": "Home Appliances",
    "climatizacao": "Home Appliances",

    # 3. Electronics & Computers
    "eletronicos": "Electronics & Computers",
    "informatica_acessorios": "Electronics & Computers",
    "audio": "Electronics & Computers",
    "pcs": "Electronics & Computers",
    "pc_gamer": "Electronics & Computers",
    "tablets_impressao_imagem": "Electronics & Computers",

    # 4. Telephony
    "telefonia": "Telephony",
    "telefonia_fixa": "Telephony",

    # 5. Fashion
    "fashion_bolsas_e_acessorios": "Fashion",
    "fashion_underwear_e_moda_praia": "Fashion",
    "fashion_roupa_masculina": "Fashion",
    "fashion_calcados": "Fashion",
    "fashion_roupa_feminina": "Fashion",
    "fashion_esporte": "Fashion",
    "fashion_roupa_infanto_juvenil": "Fashion",
    "malas_acessorios": "Fashion",

    # 6. Beauty & Personal Care
    "perfumaria": "Beauty & Personal Care",
    "beleza_saude": "Beauty & Personal Care",
    "fraldas_higiene": "Beauty & Personal Care",

    # 7. Sports & Leisure
    "esporte_lazer": "Sports & Leisure",
    "consoles_games": "Sports & Leisure",
    "instrumentos_musicais": "Sports & Leisure",
    "cool_stuff": "Sports & Leisure",

    # 8. Books & Media
    "livros_tecnicos": "Books & Media",
    "livros_interesse_geral": "Books & Media",
    "livros_importados": "Books & Media",
    "musica": "Books & Media",
    "cds_dvds_musicais": "Books & Media",
    "dvds_blu_ray": "Books & Media",

    # 9. Baby & Kids
    "bebes": "Baby & Kids",
    "brinquedos": "Baby & Kids",

    # 10. Tools & Construction
    "ferramentas_jardim": "Tools & Construction",
    "construcao_ferramentas_construcao": "Tools & Construction",
    "construcao_ferramentas_iluminacao": "Tools & Construction",
    "construcao_ferramentas_jardim": "Tools & Construction",
    "construcao_ferramentas_seguranca": "Tools & Construction",
    "construcao_ferramentas_ferramentas": "Tools & Construction",
    "casa_construcao": "Tools & Construction",

    # 11. Food & Beverages
    "alimentos": "Food & Beverages",
    "alimentos_bebidas": "Food & Beverages",
    "bebidas": "Food & Beverages",

    # 12. Automotive
    "automotivo": "Automotive",

    # 13. Pets
    "pet_shop": "Pets",

    # 14. Agriculture & Garden
    "agro_industria_e_comercio": "Agriculture & Garden",
    "flores": "Agriculture & Garden",

    # 15. Office, Arts & Services
    "papelaria": "Office, Arts & Services",
    "industria_comercio_e_negocios": "Office, Arts & Services",
    "artigos_de_festas": "Office, Arts & Services",
    "artes": "Office, Arts & Services",
    "cine_foto": "Office, Arts & Services",
    "artes_e_artesanato": "Office, Arts & Services",
    "relogios_presentes": "Office, Arts & Services",
    "market_place": "Office, Arts & Services",
    "seguros_e_servicos": "Office, Arts & Services",
    "artigos_de_natal": "Office, Arts & Services",
    "la_cuisine": "Office, Arts & Services",
}

In [26]:
ingested_df["product_category_name"]=ingested_df["product_category_name"].map(category_mapping)

In [27]:
ingested_df.head()

,order_id,customer_id,customer_unique_id,customer_city,customer_state,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,...,total_product_volume,product_category_name,seller_city,seller_state,total_payment_value,max_payment_installments,number_of_payments,payment_type,average_review_score,is_late
0,000229ec398224ef6ca0657da4fc703e,6489ae5e4333f3693df5ad4372dab6d3,3818d81c6709e39d06b2738a8d3a2474,para de minas,MG,2018-01-14 14:33:31,2018-01-14 14:48:30,2018-01-16 12:36:48,2018-01-22 13:19:16,2018-02-05,...,14157.0,Home & Furniture,borda da mata,MG,216.87,5.0,1.0,credit_card,5.0,0
1,00024acbcdf0a6daa1e931b038114c75,d4eb9395c8c0431ee92fce09860c5a06,af861d436cfc08b2c2ddefd0ba074622,atibaia,SP,2018-08-08 10:00:35,2018-08-08 10:10:18,2018-08-10 13:28:00,2018-08-14 13:32:39,2018-08-20,...,2400.0,Beauty & Personal Care,franca,SP,25.78,2.0,1.0,credit_card,4.0,0
2,00042b26cf59d7ce69dfabb4e55b4fd9,58dbd0b2d70206bf40e62cd34e84d795,64b576fb70d441e8f1b2d7d446e483c5,varzea paulista,SP,2017-02-04 13:57:51,2017-02-04 14:10:13,2017-02-16 09:46:09,2017-03-01 16:42:31,2017-03-17,...,42000.0,Tools & Construction,loanda,PR,218.04,3.0,1.0,credit_card,5.0,0
3,00054e8431b9d7675808bcb819fb4a32,32e2e6ab09e778d99bf2e0ecd4898718,635d9ac1680f03288e72ada3a1035803,guararapes,SP,2017-12-10 11:53:48,2017-12-10 12:10:31,2017-12-12 01:07:48,2017-12-18 22:03:38,2018-01-04,...,2700.0,Telephony,sao paulo,SP,31.75,1.0,1.0,credit_card,4.0,0
4,000576fe39319847cbb9d288c5617fa6,9ed5e522dd9dd85b4af4a077526d8117,fda4476abb6307ab3c415b7e6d026526,praia grande,SP,2018-07-04 12:08:27,2018-07-05 16:35:48,2018-07-05 12:15:00,2018-07-09 14:04:07,2018-07-25,...,118125.0,Tools & Construction,presidente prudente,SP,880.75,10.0,1.0,credit_card,5.0,0

In [28]:
ingested_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 96470 entries, 0 to 96469
Data columns (total 26 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       96470 non-null  str
 1   customer_id                    96470 non-null  str
 2   customer_unique_id             96470 non-null  str
 3   customer_city                  96470 non-null  str
 4   customer_state                 96470 non-null  str
 5   order_purchase_timestamp       96470 non-null  datetime64[us]
 6   order_approved_at              96456 non-null  datetime64[us]
 7   order_delivered_carrier_date   96469 non-null  datetime64[us]
 8   order_delivered_customer_date  96470 non-null  datetime64[us]
 9   order_estimated_delivery_date  96470 non-null  datetime64[us]
 10  number_of_items                96470 non-null  int64
 11  number_of_products             96470 non-null  int64
 12  number_of_sellers              96470 non-null  int64
 13  total_price                    96470 non-null  float64
 14  total_freight                  96470 non-null  float64
 15  total_product_weight           96454 non-null  float64
 16  total_product_volume           96454 non-null  float64
 17  product_category_name          95001 non-null  str
 18  seller_city                    96470 non-null  str
 19  seller_state                   96470 non-null  str
 20  total_payment_value            96469 non-null  float64
 21  max_payment_installments       96469 non-null  float64
 22  number_of_payments             96469 non-null  float64
 23  payment_type                   96469 non-null  str
 24  average_review_score           95824 non-null  float64
 25  is_late                        96470 non-null  int64
dtypes: datetime64[us](5), float64(8), int64(4), str(9)
memory usage: 19.1 MB

In [30]:
ingested_df.duplicated().sum()

np.int64(0)

In [31]:
ingested_df.isnull().sum()

order_id                            0
customer_id                         0
customer_unique_id                  0
customer_city                       0
customer_state                      0
order_purchase_timestamp            0
order_approved_at                  14
order_delivered_carrier_date        1
order_delivered_customer_date       0
order_estimated_delivery_date       0
number_of_items                     0
number_of_products                  0
number_of_sellers                   0
total_price                         0
total_freight                       0
total_product_weight               16
total_product_volume               16
product_category_name            1469
seller_city                         0
seller_state                        0
total_payment_value                 1
max_payment_installments            1
number_of_payments                  1
payment_type                        1
average_review_score              646
is_late                             0
dtype: int64

In [81]:
df = ingested_df.copy()

In [82]:
df.isnull().sum()

order_id                            0
customer_id                         0
customer_unique_id                  0
customer_city                       0
customer_state                      0
order_purchase_timestamp            0
order_approved_at                  14
order_delivered_carrier_date        1
order_delivered_customer_date       0
order_estimated_delivery_date       0
number_of_items                     0
number_of_products                  0
number_of_sellers                   0
total_price                         0
total_freight                       0
total_product_weight               16
total_product_volume               16
product_category_name            1332
seller_city                         0
seller_state                        0
total_payment_value                 1
max_payment_installments            1
number_of_payments                  1
payment_type                        1
average_review_score              646
is_late                             0
dtype: int64

In [83]:
        #columns to remove
remove_cols = [
            "order_id",
            "customer_id",
            "customer_unique_id",

            "customer_city",
            "seller_city",

            "order_delivered_carrier_date",
            "order_delivered_customer_date",

            "average_review_score"
        ]
df.drop(columns= remove_cols, inplace= True)

        #Transforming DateTime features 
df["order_purchase_hour"]= df["order_purchase_timestamp"].dt.hour
df["order_purchase_day_of_week"] = df["order_purchase_timestamp"].dt.dayofweek
df["order_purchase_month"]= df["order_purchase_timestamp"].dt.month
df["order_purchase_year"]= df["order_purchase_timestamp"].dt.year

df["order_approval_delay_hours"] = (
            df["order_approved_at"]
            - df["order_purchase_timestamp"]
        ).dt.total_seconds() / 3600

df["estimated_delivery_days"] = (
            df["order_estimated_delivery_date"]
            - df["order_purchase_timestamp"]
        ).dt.total_seconds() / 86400

df["estimated_delivery_days_after_approval"] = (
            df["order_estimated_delivery_date"]
            - df["order_approved_at"]
        ).dt.total_seconds() / 86400

In [84]:
df.isnull().sum()

customer_state                               0
order_purchase_timestamp                     0
order_approved_at                           14
order_estimated_delivery_date                0
number_of_items                              0
number_of_products                           0
number_of_sellers                            0
total_price                                  0
total_freight                                0
total_product_weight                        16
total_product_volume                        16
product_category_name                     1332
seller_state                                 0
total_payment_value                          1
max_payment_installments                     1
number_of_payments                           1
payment_type                                 1
is_late                                      0
order_purchase_hour                          0
order_purchase_day_of_week                   0
order_purchase_month                         0
order_purchase_year                          0
order_approval_delay_hours                  14
estimated_delivery_days                      0
estimated_delivery_days_after_approval      14
dtype: int64

In [39]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 96470 entries, 0 to 96469
Data columns (total 25 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   customer_state                          96470 non-null  str
 1   order_purchase_timestamp                96470 non-null  datetime64[us]
 2   order_approved_at                       96456 non-null  datetime64[us]
 3   order_estimated_delivery_date           96470 non-null  datetime64[us]
 4   number_of_items                         96470 non-null  int64
 5   number_of_products                      96470 non-null  int64
 6   number_of_sellers                       96470 non-null  int64
 7   total_price                             96470 non-null  float64
 8   total_freight                           96470 non-null  float64
 9   total_product_weight                    96454 non-null  float64
 10  total_product_volume                    96454 non-null  float64
 11  product_category_name                   95001 non-null  str
 12  seller_state                            96470 non-null  str
 13  total_payment_value                     96469 non-null  float64
 14  max_payment_installments                96469 non-null  float64
 15  number_of_payments                      96469 non-null  float64
 16  payment_type                            96469 non-null  str
 17  is_late                                 96470 non-null  int64
 18  order_purchase_hour                     96470 non-null  int32
 19  order_purchase_day_of_week              96470 non-null  int32
 20  order_purchase_month                    96470 non-null  int32
 21  order_purchase_year                     96470 non-null  int32
 22  order_approval_delay_hours              96456 non-null  float64
 23  estimated_delivery_days                 96470 non-null  float64
 24  estimated_delivery_days_after_approval  96456 non-null  float64
dtypes: datetime64[us](3), float64(10), int32(4), int64(4), str(4)
memory usage: 16.9 MB

In [85]:
#dealing with null values in categorical 
df.payment_type.unique()

<StringArray>
['credit_card', 'boleto', 'debit_card', 'voucher', nan]
Length: 5, dtype: str

In [86]:
df.product_category_name.unique()

<StringArray>
[                                    'cool_stuff',
                               'moveis_decoracao',
                                     'perfumaria',
                             'ferramentas_jardim',
                                      'telefonia',
                                   'beleza_saude',
                    'fashion_bolsas_e_acessorios',
                                'cama_mesa_banho',
                                  'esporte_lazer',
                                 'consoles_games',
                              'moveis_escritorio',
                                      'alimentos',
                      'agro_industria_e_comercio',
                                    'eletronicos',
              'construcao_ferramentas_construcao',
                         'informatica_acessorios',
                                       'pet_shop',
                                'livros_tecnicos',
                                          'bebes',
              'construcao_ferramentas_iluminacao',
                                     'brinquedos',
                                      'papelaria',
                          'utilidades_domesticas',
                  'industria_comercio_e_negocios',
                             'relogios_presentes',
                                     'automotivo',
                                              nan,
                               'eletrodomesticos',
                                  'casa_conforto',
                    'portateis_casa_forno_e_cafe',
                                'fraldas_higiene',
                                   'climatizacao',
                                'eletroportateis',
                  'construcao_ferramentas_jardim',
                          'instrumentos_musicais',
                                'casa_construcao',
                         'livros_interesse_geral',
                              'artigos_de_festas',
 'moveis_cozinha_area_de_servico_jantar_e_jardim',
                               'malas_acessorios',
               'construcao_ferramentas_seguranca',
                                 'telefonia_fixa',
                                      'cine_foto',
                 'fashion_underwear_e_moda_praia',
                              'alimentos_bebidas',
                                        'bebidas',
                        'sinalizacao_e_seguranca',
                                   'market_place',
                                    'moveis_sala',
                                          'artes',
                               'fashion_calcados',
                                         'flores',
                             'eletrodomesticos_2',
                         'fashion_roupa_feminina',
                                          'audio',
                                            'pcs',
                        'fashion_roupa_masculina',
                                         'musica',
                                  'moveis_quarto',
                               'artigos_de_natal',
  'portateis_cozinha_e_preparadores_de_alimentos',
                              'livros_importados',
                                   'dvds_blu_ray',
                              'cds_dvds_musicais',
                             'artes_e_artesanato',
                       'tablets_impressao_imagem',
                                'casa_conforto_2',
             'construcao_ferramentas_ferramentas',
                      'moveis_colchao_e_estofado',
                                'fashion_esporte',
                                       'pc_gamer',
                                     'la_cuisine',
                             'seguros_e_servicos',
                  'fashion_roupa_infanto_juvenil']
Length: 74, dtype: str

In [ ]:
import numpy as np

In [87]:
category_mapping = {

            # 1. Home & Furniture
            "moveis_decoracao": "Home & Furniture",
            "cama_mesa_banho": "Home & Furniture",
            "utilidades_domesticas": "Home & Furniture",
            "moveis_escritorio": "Home & Furniture",
            "moveis_cozinha_area_de_servico_jantar_e_jardim": "Home & Furniture",
            "casa_conforto": "Home & Furniture",
            "moveis_sala": "Home & Furniture",
            "moveis_quarto": "Home & Furniture",
            "casa_conforto_2": "Home & Furniture",
            "moveis_colchao_e_estofado": "Home & Furniture",

            # 2. Home Appliances
            "eletrodomesticos": "Home Appliances",
            "portateis_casa_forno_e_cafe": "Home Appliances",
            "eletroportateis": "Home Appliances",
            "eletrodomesticos_2": "Home Appliances",
            "portateis_cozinha_e_preparadores_de_alimentos": "Home Appliances",
            "climatizacao": "Home Appliances",

            # 3. Electronics & Computers
            "eletronicos": "Electronics & Computers",
            "informatica_acessorios": "Electronics & Computers",
            "audio": "Electronics & Computers",
            "pcs": "Electronics & Computers",
            "pc_gamer": "Electronics & Computers",
            "tablets_impressao_imagem": "Electronics & Computers",

            # 4. Telephony
            "telefonia": "Telephony",
            "telefonia_fixa": "Telephony",

            # 5. Fashion
            "fashion_bolsas_e_acessorios": "Fashion",
            "fashion_underwear_e_moda_praia": "Fashion",
            "fashion_roupa_masculina": "Fashion",
            "fashion_calcados": "Fashion",
            "fashion_roupa_feminina": "Fashion",
            "fashion_esporte": "Fashion",
            "fashion_roupa_infanto_juvenil": "Fashion",
            "malas_acessorios": "Fashion",

            # 6. Beauty & Personal Care
            "perfumaria": "Beauty & Personal Care",
            "beleza_saude": "Beauty & Personal Care",
            "fraldas_higiene": "Beauty & Personal Care",

            # 7. Sports & Leisure
            "esporte_lazer": "Sports & Leisure",
            "consoles_games": "Sports & Leisure",
            "instrumentos_musicais": "Sports & Leisure",
            "cool_stuff": "Sports & Leisure",

            # 8. Books & Media
            "livros_tecnicos": "Books & Media",
            "livros_interesse_geral": "Books & Media",
            "livros_importados": "Books & Media",
            "musica": "Books & Media",
            "cds_dvds_musicais": "Books & Media",
            "dvds_blu_ray": "Books & Media",

            # 9. Baby & Kids
            "bebes": "Baby & Kids",
            "brinquedos": "Baby & Kids",

            # 10. Tools & Construction
            "ferramentas_jardim": "Tools & Construction",
            "construcao_ferramentas_construcao": "Tools & Construction",
            "construcao_ferramentas_iluminacao": "Tools & Construction",
            "construcao_ferramentas_jardim": "Tools & Construction",
            "construcao_ferramentas_seguranca": "Tools & Construction",
            "construcao_ferramentas_ferramentas": "Tools & Construction",
            "casa_construcao": "Tools & Construction",

            # 11. Food & Beverages
            "alimentos": "Food & Beverages",
            "alimentos_bebidas": "Food & Beverages",
            "bebidas": "Food & Beverages",

            # 12. Automotive
            "automotivo": "Automotive",

            # 13. Pets
            "pet_shop": "Pets",

            # 14. Agriculture & Garden
            "agro_industria_e_comercio": "Agriculture & Garden",
            "flores": "Agriculture & Garden",

            # 15. Office, Arts & Services
            "papelaria": "Office, Arts & Services",
            "industria_comercio_e_negocios": "Office, Arts & Services",
            "artigos_de_festas": "Office, Arts & Services",
            "artes": "Office, Arts & Services",
            "cine_foto": "Office, Arts & Services",
            "artes_e_artesanato": "Office, Arts & Services",
            "relogios_presentes": "Office, Arts & Services",
            "market_place": "Office, Arts & Services",
            "seguros_e_servicos": "Office, Arts & Services",
            "artigos_de_natal": "Office, Arts & Services",
            "la_cuisine": "Office, Arts & Services",
           
        }
df["product_category_name"]=df["product_category_name"].map(category_mapping)

In [88]:
df["payment_type"]=df["payment_type"].fillna("unknown")

In [93]:
df.isnull().sum()

customer_state                             0
order_purchase_timestamp                   0
order_approved_at                         14
order_estimated_delivery_date              0
number_of_items                            0
number_of_products                         0
number_of_sellers                          0
total_price                                0
total_freight                              0
total_product_weight                      16
total_product_volume                      16
product_category_name                      0
seller_state                               0
total_payment_value                        1
max_payment_installments                   1
number_of_payments                         1
payment_type                               0
is_late                                    0
order_purchase_hour                        0
order_purchase_day_of_week                 0
order_purchase_month                       0
order_purchase_year                        0
order_approval_delay_hours                14
estimated_delivery_days                    0
estimated_delivery_days_after_approval    14
dtype: int64

In [91]:
df.product_category_name.unique()

<StringArray>
[       'Sports & Leisure',        'Home & Furniture',
  'Beauty & Personal Care',    'Tools & Construction',
               'Telephony',                 'Fashion',
        'Food & Beverages',    'Agriculture & Garden',
 'Electronics & Computers',                    'Pets',
           'Books & Media',             'Baby & Kids',
 'Office, Arts & Services',              'Automotive',
                       nan,         'Home Appliances']
Length: 16, dtype: str

In [92]:
df["product_category_name"]= df["product_category_name"].fillna("unknown")

In [94]:
timestamp_cols = ['order_purchase_timestamp', 'order_approved_at', 'order_estimated_delivery_date']
df.drop(columns=timestamp_cols, inplace= True)

In [95]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 96470 entries, 0 to 96469
Data columns (total 22 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   customer_state                          96470 non-null  str
 1   number_of_items                         96470 non-null  int64
 2   number_of_products                      96470 non-null  int64
 3   number_of_sellers                       96470 non-null  int64
 4   total_price                             96470 non-null  float64
 5   total_freight                           96470 non-null  float64
 6   total_product_weight                    96454 non-null  float64
 7   total_product_volume                    96454 non-null  float64
 8   product_category_name                   96470 non-null  str
 9   seller_state                            96470 non-null  str
 10  total_payment_value                     96469 non-null  float64
 11  max_payment_installments                96469 non-null  float64
 12  number_of_payments                      96469 non-null  float64
 13  payment_type                            96470 non-null  str
 14  is_late                                 96470 non-null  int64
 15  order_purchase_hour                     96470 non-null  int32
 16  order_purchase_day_of_week              96470 non-null  int32
 17  order_purchase_month                    96470 non-null  int32
 18  order_purchase_year                     96470 non-null  int32
 19  order_approval_delay_hours              96456 non-null  float64
 20  estimated_delivery_days                 96470 non-null  float64
 21  estimated_delivery_days_after_approval  96456 non-null  float64
dtypes: float64(10), int32(4), int64(4), str(4)
memory usage: 14.7 MB